### ISSUE TITLE
How do I copy files to RAM?

### ISSUE THREAD

**Issue by JustinBustin5** [pbatard/UEFI-Shell#3]
I've seen a command called ```ramdisk``` used on a website but it's either not on this UEFI shell or it's an alias that they made.

**Comment by pbatard** [comment]
This repository does not provide support for UEFI Shell related questions (we're providing binaries based on the [official EDK2 project](https://github.com/tianocore/edk2) and that's pretty much it). So your question should probably be posted to the [EDK2 discuss mailing list](https://edk2.groups.io/g/discuss).
