### ISSUE TITLE
dmem with -mmio .. does it not support mappings in MMIOH / 64bit space ?

### ISSUE THREAD

**Issue by lc99sj** [pbatard/UEFI-Shell#4]
I believe I found that  `dmem`  doesn't support accessing  MMIOH  space ( ? )
When the address range is above the 32bit ( MMIOL ) boundary ( ? )
Can someone help me to understand this :
( **1** )  `mm`  works as you would expect,
```
Shell> mm -w 4 10a002000000 -mmio -n
MMIO  0x000010A002000000 : 0x180000A1
```
( **2** )  But `dmem` does not work, in this case.  Did it ever ?
```
Shell> dmem -b 10a002000000 4 -mmio
dmem: Problem accessing the data using Protocol - PciRootBridgeIo

Shell> dmem 10a002000000 4 -mmio
dmem: Problem accessing the data using Protocol - PciRootBridgeIo

Shell> dmem 0x10a002000000 4 -mmio
dmem: Problem accessing the data using Protocol - PciRootBridgeIo
```

**Comment by pbatard** [comment]
This repository does not provide support for UEFI Shell related questions (we're providing binaries based on the [official EDK2 project](https://github.com/tianocore/edk2) and that's pretty much it). So your question should probably be posted to the [EDK2 discuss mailing list](https://edk2.groups.io/g/discuss).

**Comment by lc99sj** [comment]
Yes, thanks Pete - you're right and I should follow that recommendation.
I just came back here to say that I was actually  _**wrong**_  about the issue.
I believe the confusion ( or maybe wrongness ) is that you'd  **think**  these device accesses
should be called using `-mmio` but actually it's that ( `-mmio` )
  i.e. requesting "device memory" display via `EFI_PCI_ROOT_BRIDGE_IO_PROTOCOL`
     that makes them fail.  ( Never mind the MMIOH or MMIOL )
Here's a brief example to correct my original message, above.  ( Sorry I had this wrong, earlier )  Thanks
```
FS0:\> dmem 10a002000000 4          # 1. MMIOH is OK
Memory Address 000010A002000000 4 Bytes
  02000000: A1 00 00 18                                      *....*

FS0:\> dmem 10a002000000 4 -mmio    # 2. But not via Root Bridge I/O ..
dmem: Problem accessing the data using Protocol - PciRootBridgeIo

FS0:\> dmem e0000000 4              # 3. Access via MCFG is OK
Memory Address 00000000E0000000 4 Bytes
  E0000000: 22 10 A4 14                                      *"...*

FS0:\> dmem e0000000 4 -mmio        # 4. But not via Root Bridge I/O ..
dmem: Problem accessing the data using Protocol - PciRootBridgeIo
```
